#!/usr/bin/env python3
# =======================================================================
# tools/gen_decode_vectors.py
#
#   python3 tools/gen_decode_vectors.py > tests/vec_decode.cst
#
# Canned compressed bodies for tests/test_decode.cst, built with Python's own
# gzip and zlib so that what this library decodes is what a different
# implementation encoded — a round trip through caustic-compact alone would
# only prove it agrees with itself.
#
# "deflate" appears twice on purpose. The header name says deflate; servers
# send it BOTH zlib-wrapped (RFC 1950) and raw (RFC 1951), and they always
# have. A client that trusts the name gets one of the two wrong, so decode.cst
# sniffs, and both shapes are here to prove the sniff.
#
# BOMB is 8 MiB of zeros gzipped. Its ratio is about 1027 to 1, which is
# roughly the most DEFLATE's 32 KiB window can achieve, and it is here to be
# refused rather than decoded.
# =======================================================================

import gzip
import sys
import zlib

PLAIN = b"the quick brown fox jumps over the lazy dog, repeatedly. " * 8
BOMB_PLAIN = 8 * 1024 * 1024


def cstr(b):
    return '"' + "".join("\\x%02x" % c for c in b) + '"'


def main():
    co = zlib.compressobj(wbits=-15)
    raw = co.compress(PLAIN) + co.flush()
    bomb = gzip.compress(b"\x00" * BOMB_PLAIN)

    w = sys.stdout.write
    w("// =======================================================\n")
    w("// caustic-net/tests/vec_decode.cst\n")
    w("// Canned compressed bodies.\n")
    w("//\n")
    w("// GENERATED by tools/gen_decode_vectors.py; see that file for why each\n")
    w("// one is here. Built with Python's gzip and zlib, so what this library\n")
    w("// decodes is what a different implementation encoded.\n")
    w("//\n")
    w("// BOMB is %d MiB of zeros gzipped: %d bytes expanding %d to 1.\n"
      % (BOMB_PLAIN // 1024 // 1024, len(bomb), BOMB_PLAIN // len(bomb)))
    w("// =======================================================\n\n")

    w("let is *u8 as PLAIN with imut =\n    %s;\n" % cstr(PLAIN))
    w("let is i64 as PLAIN_N with imut = %d;\n\n" % len(PLAIN))

    for name, blob, note in (
        ("GZIP", gzip.compress(PLAIN), "gzip"),
        ("ZLIB", zlib.compress(PLAIN), "deflate, zlib-wrapped (RFC 1950)"),
        ("RAW", raw, "deflate, raw (RFC 1951) — the same header name"),
    ):
        w("// %s\n" % note)
        w("let is *u8 as %s with imut =\n    %s;\n" % (name, cstr(blob)))
        w("let is i64 as %s_N with imut = %d;\n\n" % (name, len(blob)))

    w("// 8 MiB of zeros. To be refused, not decoded.\n")
    w("let is *u8 as BOMB with imut =\n    %s;\n" % cstr(bomb))
    w("let is i64 as BOMB_N with imut = %d;\n" % len(bomb))
    w("let is i64 as BOMB_PLAIN with imut = %d;\n" % BOMB_PLAIN)


if __name__ == "__main__":
    main()
